"""Load DIPL, derive custom code units, validate, and render Arepo files."""

from __future__ import annotations

import os
from pathlib import Path
import tempfile
from typing import Any

from scinumtools3.dip import Adapter, run_adapter

from .rendering import GenerationError, format_value, render_native, value_at
from .tables import render_tables


ROOT = Path(__file__).resolve().parents[2]
EXAMPLES = ROOT / "examples"
SETUPS = {manifest.parent.name: manifest for manifest in sorted(EXAMPLES.glob("*/DIPfile"))}


def _require_dipl() -> Any:
    try:
        from scinumtools3.dip import DIP  # type: ignore
    except ImportError as exc:
        raise GenerationError(
            "SciNumTools3 Python bindings are required. Build/install snt3 before generating artifacts."
        ) from exc
    return DIP


_value = value_at


def load_environment(setup: str = "cosmological_star_formation") -> Any:
    """Load one self-contained DIPL setup and its reference-derived units."""
    DIP = _require_dipl()
    try:
        manifest = SETUPS[setup]
    except KeyError as exc:
        raise GenerationError(f"Unknown setup `{setup}`. Choose one of: {', '.join(SETUPS)}.") from exc
    dip = DIP()
    dip.add_project(manifest)
    return dip.parse()


def _collection_values(env: Any, fqp: str, member: str = "length") -> list[Any]:
    """Read a named value below each DIPL collection-item container."""
    values: list[Any] = []
    index = 0
    while True:
        try:
            values.append(_value(env, f"{fqp}[{index}].{member}"))
        except GenerationError:
            return values
        index += 1


def _render_config(env: Any) -> str:
    lines = ["#!/bin/bash", "# Generated by dip/src/arepo_dipl; do not edit.", ""]
    return "\n".join(lines + render_native(env, "config")) + "\n"


def _render_parameters(env: Any) -> str:
    lines = ["% Generated by dip/src/arepo_dipl; do not edit.", "% DIPL environment and provenance are in environment.diph5.", ""]
    lines.extend(render_native(env, "param"))
    # Arepo exposes these as indexed flat tag families, while the semantic
    # model retains their collection meaning and unit validation.
    for native_prefix, fqp in (
        ("SofteningComovingType", "gravity.softenings.comoving"),
        ("SofteningMaxPhysType", "gravity.softenings.physical_maximum"),
    ):
        for index, value in enumerate(_collection_values(env, fqp)):
            lines.extend((
                f"% DIPL {fqp}[{index}]: gravitational softening in arepo_length.",
                f"{native_prefix}{index:<22}{format_value(value)}",
            ))
    for index, value in enumerate(_value(env, "gravity.softenings.particle_type_map")):
        lines.extend((
            f"% DIPL gravity.softenings.particle_type_map[{index}].",
            f"SofteningTypeOfPartType{index:<19}{format_value(value)}",
        ))
    return "\n".join(lines) + "\n"


def _render_schedule(env: Any) -> str:
    if not _value(env, "output.schedule.enabled"):
        return ""
    coordinate = _value(env, "simulation.time.coordinate")
    column = "scale_factor" if coordinate == "scale_factor" else "time"
    times = _value(env, f"output_schedule.{column}")
    flags = _value(env, "output_schedule.write_flag")
    # SNT unwraps singleton arrays in its Python value accessor.
    times = times if isinstance(times, list) else [times]
    flags = flags if isinstance(flags, list) else [flags]
    if len(times) != len(flags):
        raise GenerationError("Output schedule times and write flags must have equal lengths.")
    return "\n".join(f"{a:.12g} {int(b)}" for a, b in zip(times, flags)) + "\n"


def generate(output: Path, setup: str = "cosmological_star_formation") -> Path:
    env = load_environment(setup)
    adapter = ArepoAdapter()
    if not output.exists() and not output.is_symlink():
        run_adapter(env, adapter, output, "environment.diph5")
        return output

    if not output.is_dir() or output.is_symlink():
        raise GenerationError(f"Invalid output directory `{output}`.")
    # SNT3 refuses to overwrite files. Stage a fresh run, then replace only
    # generated files so an existing compiled executable and build stay intact.
    with tempfile.TemporaryDirectory(prefix="arepo-dipl-", dir=output.parent) as directory:
        stage = Path(directory)
        written = run_adapter(env, adapter, stage, "environment.diph5")
        destinations = [(source, output / source.relative_to(stage)) for source in written]
        root = output.resolve()
        for _, destination in destinations:
            if (not destination.resolve().is_relative_to(root) or destination.is_symlink()
                    or destination.exists() and not destination.is_file()):
                raise GenerationError(f"Invalid or conflicting output path `{destination}`.")
            parent = destination.parent
            while parent != output:
                if parent.is_symlink() or parent.exists() and not parent.is_dir():
                    raise GenerationError(f"Invalid or conflicting output path `{destination}`.")
                parent = parent.parent
        for source, destination in destinations:
            destination.parent.mkdir(parents=True, exist_ok=True)
            os.replace(source, destination)
    return output


class ArepoAdapter(Adapter):
    """Plan the native files for an evaluated Arepo environment."""

    def plan(self, env: Any, context: Any) -> None:
        context.add_text("Config.sh", _render_config(env))
        context.add_text("param.txt", _render_parameters(env))
        if _value(env, "output.schedule.enabled"):
            context.add_text(Path(_value(env, "output.schedule.filename")), _render_schedule(env))
        for filename, content in render_tables(env).items():
            context.add_text(Path(filename), content)
