"""Load DIPL, derive custom code units, validate, and render Arepo files."""

from __future__ import annotations

from pathlib import Path
from typing import Any

from .rendering import GenerationError, format_value, render_native, value_at
from .tables import render_tables


ROOT = Path(__file__).resolve().parents[2]
EXAMPLES = ROOT / "examples"
SETUPS = {manifest.parent.name: manifest for manifest in sorted(EXAMPLES.glob("*/DIPfile"))}


def _require_dipl() -> Any:
    try:
        from scinumtools3.dip import DIP  # type: ignore
    except ImportError as exc:
        raise GenerationError(
            "SciNumTools3 Python bindings are required. Build/install snt3 before generating artifacts."
        ) from exc
    return DIP


_value = value_at


def load_environment(setup: str = "cosmological_star_formation") -> Any:
    """Load one self-contained DIPL setup and its reference-derived units."""
    DIP = _require_dipl()
    try:
        manifest = SETUPS[setup]
    except KeyError as exc:
        raise GenerationError(f"Unknown setup `{setup}`. Choose one of: {', '.join(SETUPS)}.") from exc
    dip = DIP()
    dip.add_project(manifest)
    return dip.parse()


def _collection_values(env: Any, fqp: str, member: str = "length") -> list[Any]:
    """Read a named value below each DIPL collection-item container."""
    values: list[Any] = []
    index = 0
    while True:
        try:
            values.append(_value(env, f"{fqp}[{index}].{member}"))
        except GenerationError:
            return values
        index += 1


def _render_config(env: Any) -> str:
    lines = ["#!/bin/bash", "# Generated by dip/src/arepo_dipl; do not edit.", ""]
    return "\n".join(lines + render_native(env, "config")) + "\n"


def _render_parameters(env: Any) -> str:
    lines = ["% Generated by dip/src/arepo_dipl; do not edit.", "% DIPL environment and provenance are in environment.diph5.", ""]
    lines.extend(render_native(env, "param"))
    # Arepo exposes these as indexed flat tag families, while the semantic
    # model retains their collection meaning and unit validation.
    for native_prefix, fqp in (
        ("SofteningComovingType", "gravity.softenings.comoving"),
        ("SofteningMaxPhysType", "gravity.softenings.physical_maximum"),
    ):
        for index, value in enumerate(_collection_values(env, fqp)):
            lines.extend((
                f"% DIPL {fqp}[{index}]: gravitational softening in arepo_length.",
                f"{native_prefix}{index:<22}{format_value(value)}",
            ))
    for index, value in enumerate(_value(env, "gravity.softenings.particle_type_map")):
        lines.extend((
            f"% DIPL gravity.softenings.particle_type_map[{index}].",
            f"SofteningTypeOfPartType{index:<19}{format_value(value)}",
        ))
    return "\n".join(lines) + "\n"


def _render_schedule(env: Any) -> str:
    if not _value(env, "output.schedule.enabled"):
        return ""
    coordinate = _value(env, "simulation.time.coordinate")
    column = "scale_factor" if coordinate == "scale_factor" else "time"
    times = _value(env, f"output_schedule.{column}")
    flags = _value(env, "output_schedule.write_flag")
    # SNT unwraps singleton arrays in its Python value accessor.
    times = times if isinstance(times, list) else [times]
    flags = flags if isinstance(flags, list) else [flags]
    if len(times) != len(flags):
        raise GenerationError("Output schedule times and write flags must have equal lengths.")
    return "\n".join(f"{a:.12g} {int(b)}" for a, b in zip(times, flags)) + "\n"


def generate(output: Path, setup: str = "cosmological_star_formation") -> Path:
    env = load_environment(setup)
    datasets = render_tables(env)
    reserved = {"Config.sh", "param.txt", "output_list.txt", "environment.diph5"}
    destinations = {}
    for filename, content in datasets.items():
        destination = (output / filename).resolve()
        if (not destination.is_relative_to(output.resolve()) or destination == output.resolve()
                or destination.name in reserved or destination in destinations):
            raise GenerationError(f"Invalid or conflicting dataset output path `{filename}`.")
        destinations[destination] = content
    output.mkdir(parents=True, exist_ok=True)
    (output / "Config.sh").write_text(_render_config(env))
    (output / "param.txt").write_text(_render_parameters(env))
    (output / "output_list.txt").write_text(_render_schedule(env))
    env.save(output / "environment.diph5")
    for destination, content in destinations.items():
        destination.parent.mkdir(parents=True, exist_ok=True)
        destination.write_text(content)
    return output
